name: Auto Sign-in for BBS & IKUUU
on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '10 23 * * *'
  workflow_dispatch:

jobs:
  sign_in_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 设定北京时间
        uses: szenius/set-timezone@v2.0
        with:
          timezone: Asia/Shanghai

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests playwright
          pip install git+https://github.com/qqhsx/my-utils.git

      - name: Install Playwright Browsers
        run: |
          playwright install chromium

      - name: Run sign-in script + 钉钉推送
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
          DING_WEBHOOK: ${{ secrets.DING_WEBHOOK }}
        run: |
          set +e
          res=$(python sign_ikuuu.py 2> err.log)
          ret_code=$?
          echo "脚本退出码：$ret_code"
          echo "脚本标准输出：$res"
          echo "脚本错误日志："
          cat err.log
          curl -s -X POST "${DING_WEBHOOK}" \
          -H "Content-Type:application/json" \
          -d "{\"msgtype\":\"text\",\"text\":{\"content\":\"# IKUUU自动签到通知\n🕒执行时间：$(date +'%Y-%m-%d %H:%M:%S')\n📋签到结果：\n$res\n🔙脚本退出码：$ret_code\"}}" \
          || true
